name: Upload Translation Keys to SimpleLocalize

on:
  workflow_dispatch:

jobs:
  Upload-Translation-Keys:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Extract Translation Keys
        run: |
          yarn install
          yarn extract src/**/*.tsx --out-file SimpleLocalize/en.json --format simple

      - name: Upload Translation Keys
        run: |
          curl -s https://get.simplelocalize.io/install | bash
          simplelocalize upload 
            --apiKey ${{secrets.SIMPLELOCALIZEAPIKEY}} 
            --uploadPath SimpleLocalize/en.json 
            --uploadFormat single-language-json
            --languageKey en
